/* LinkFinder sample dataset — development data.
 * Descriptions, categorisation and pricing notes are written for this project.
 * linkStatus is "unchecked" for every entry: no automated URL check has run
 * against these hosts yet, so the UI must not claim otherwise. */

window.LINKFINDER_CATEGORIES = [
  { name: 'AI & Machine Learning', icon: '✦', desc: 'Models, assistants and ML tooling', hue: 'cyan' },
  { name: 'Cybersecurity', icon: '⌁', desc: 'Defend, investigate and assess', hue: 'amber' },
  { name: 'Developer Tools', icon: '◈', desc: 'Build, ship and debug faster', hue: 'blue' },
  { name: 'Design', icon: '◫', desc: 'Craft for screens and print', hue: 'purple' },
  { name: 'Education', icon: '◎', desc: 'Structured learning, free and paid', hue: 'green' },
  { name: 'Productivity', icon: '▦', desc: 'Notes, tasks and focus systems', hue: 'cyan' },
  { name: 'Business', icon: '▣', desc: 'Run the operational side', hue: 'blue' },
  { name: 'Finance', icon: '◌', desc: 'Money, markets and bookkeeping', hue: 'green' },
  { name: 'Cloud & Hosting', icon: '⌘', desc: 'Infrastructure and deployment', hue: 'purple' },
  { name: 'Software', icon: '▩', desc: 'Everyday desktop applications', hue: 'amber' },
  { name: 'Media', icon: '▷', desc: 'Watch, read, listen and archive', hue: 'purple' },
  { name: 'Gaming', icon: '◐', desc: 'Stores, modding and discovery', hue: 'blue' },
  { name: 'OSINT & Research', icon: '⌖', desc: 'Find signal in public sources', hue: 'amber' },
  { name: 'Science', icon: '⚛', desc: 'Papers, data and simulation', hue: 'green' },
  { name: 'Career & Jobs', icon: '⇄', desc: 'Find work, pay data and levelling', hue: 'cyan' },
  { name: 'Marketing', icon: '◈', desc: 'Reach, measure and analyse', hue: 'purple' },
  { name: 'Social Media', icon: '◈', desc: 'Communities and messaging', hue: 'blue' },
  { name: 'Web Tools', icon: '⌗', desc: 'Small utilities that solve one job', hue: 'green' }
];

const S = [
  // AI & Machine Learning
  ['ChatGPT', 'AI & Machine Learning', 'Conversational assistant for writing, coding and research, with image generation built in.', 'https://chatgpt.com', ['Chat', 'Writing'], 'Freemium', ''],
  ['Claude', 'AI & Machine Learning', 'Anthropic assistant known for long-context reading and careful, structured writing.', 'https://claude.ai', ['Chat', 'Writing'], 'Freemium', 'amber'],
  ['Google Gemini', 'AI & Machine Learning', 'Multimodal assistant integrated across Google apps, with a free tier.', 'https://gemini.google.com', ['Chat', 'Multimodal'], 'Freemium', 'blue'],
  ['Perplexity', 'AI & Machine Learning', 'Answer engine that searches the web and shows citations for each claim.', 'https://www.perplexity.ai', ['Search', 'Research'], 'Freemium', ''],
  ['Hugging Face', 'AI & Machine Learning', 'The main public hub for datasets, model weights and demo Spaces.', 'https://huggingface.co', ['Models', 'Open source'], 'Freemium', 'amber'],
  ['Ollama', 'AI & Machine Learning', 'Run open models locally on your own machine with a single command.', 'https://ollama.com', ['Local', 'Open source'], 'Free', 'green'],
  ['Replicate', 'AI & Machine Learning', 'Run community models through a hosted API without managing GPUs.', 'https://replicate.com', ['API', 'Models'], 'Pay as you go', ''],
  ['Groq', 'AI & Machine Learning', 'Inference API built on LPUs, unusually fast for open-weight models.', 'https://console.groq.com', ['API', 'Inference'], 'Free tier', 'amber'],
  ['OpenRouter', 'AI & Machine Learning', 'One API key that routes requests across many model providers.', 'https://openrouter.ai', ['API', 'Routing'], 'Pay as you go', 'green'],
  ['ElevenLabs', 'AI & Machine Learning', 'High-quality text-to-speech and voice cloning in many languages.', 'https://elevenlabs.io', ['Audio', 'Voice'], 'Freemium', 'purple'],
  ['LangChain', 'AI & Machine Learning', 'Framework for composing chains, tools and retrieval around language models.', 'https://www.langchain.com', ['Framework', 'Code'], 'Free', ''],
  ['Runway', 'AI & Machine Learning', 'Video generation and editing model suite for creators.', 'https://runwayml.com', ['Video', 'Creative'], 'Freemium', 'purple'],
  ['Kaggle', 'AI & Machine Learning', 'Datasets, notebooks and competitions for machine learning practice.', 'https://www.kaggle.com', ['Datasets', 'Learning'], 'Free', 'blue'],

  // Cybersecurity
  ['Have I Been Pwned', 'Cybersecurity', 'Check whether an email address appears in a known data breach.', 'https://haveibeenpwned.com', ['Privacy', 'Breaches'], 'Free', 'amber'],
  ['VirusTotal', 'Cybersecurity', 'Scan files and URLs against dozens of antivirus engines at once.', 'https://www.virustotal.com', ['Malware', 'Scanning'], 'Freemium', 'blue'],
  ['Shodan', 'Cybersecurity', 'Search engine that indexes internet-connected devices and banners.', 'https://www.shodan.io', ['Recon', 'IoT'], 'Freemium', 'amber'],
  ['Censys', 'Cybersecurity', 'Continuous scanning of hosts, certificates and services on the public internet.', 'https://search.censys.io', ['Recon', 'Assets'], 'Freemium', 'purple'],
  ['Maltego', 'Cybersecurity', 'Link analysis for building graphs of entities from OSINT sources.', 'https://www.maltego.com', ['Link analysis', 'OSINT'], 'Freemium', 'purple'],
  ['OWASP ZAP', 'Cybersecurity', 'Open source web application scanner for finding common vulnerabilities.', 'https://www.zaproxy.org', ['AppSec', 'Open source'], 'Free', 'green'],
  ['CyberChef', 'Cybersecurity', 'Browser toolchain of operations for encoding, decoding and forensics.', 'https://gchq.github.io/CyberChef/', ['Forensics', 'Utility'], 'Free', 'green'],
  ['Mullvad', 'Cybersecurity', 'Privacy-focused VPN with anonymous account creation and flat pricing.', 'https://mullvad.net', ['VPN', 'Privacy'], 'Paid', 'amber'],
  ['Proton Pass', 'Cybersecurity', 'End-to-end encrypted password manager with secure sharing.', 'https://proton.me/pass', ['Passwords', 'Privacy'], 'Freemium', 'purple'],
  ['SecurityTrails', 'Cybersecurity', 'Historical DNS records and domain intelligence for investigations.', 'https://securitytrails.com', ['DNS', 'Recon'], 'Freemium', 'blue'],

  // Developer Tools
  ['GitHub', 'Developer Tools', 'Where the majority of software is hosted, reviewed and built.', 'https://github.com', ['Code', 'Hosting'], 'Freemium', ''],
  ['GitLab', 'Developer Tools', 'Full DevOps platform covering repositories, CI and artifact registries.', 'https://gitlab.com', ['Code', 'CI'], 'Freemium', 'amber'],
  ['Stack Overflow', 'Developer Tools', 'Question and answer site for specific programming problems.', 'https://stackoverflow.com', ['Q&A', 'Community'], 'Freemium', 'orange'],
  ['CodePen', 'Developer Tools', 'Browser playground for front-end work with live previews and sharing.', 'https://codepen.io', ['Sandbox', 'Front end'], 'Freemium', 'amber'],
  ['Replit', 'Developer Tools', 'Browser IDE that runs and hosts your project without local setup.', 'https://replit.com', ['IDE', 'Hosting'], 'Freemium', 'green'],
  ['MDN Web Docs', 'Developer Tools', 'Reference documentation for HTML, CSS, JavaScript and browser APIs.', 'https://developer.mozilla.org', ['Docs', 'Reference'], 'Free', 'blue'],
  ['Regex101', 'Developer Tools', 'Build and test regular expressions with explanations as you type.', 'https://regex101.com', ['Utility', 'Text'], 'Freemium', 'green'],
  ['Can I Use', 'Developer Tools', 'Browser support tables for web platform features and devices.', 'https://caniuse.com', ['Compatibility', 'Reference'], 'Free', 'amber'],
  ['Postman', 'Developer Tools', 'Design, test and document HTTP APIs from a graphical client.', 'https://www.postman.com', ['API', 'Testing'], 'Freemium', 'blue'],
  ['Prisma', 'Developer Tools', 'Type-safe database client and schema toolkit for TypeScript projects.', 'https://www.prisma.io', ['Database', 'TypeScript'], 'Free', 'purple'],
  ['Dev.to', 'Developer Tools', 'Publishing platform where developers write about what they are building.', 'https://dev.to', ['Community', 'Writing'], 'Free', 'blue'],

  // Design
  ['Figma', 'Design', 'Collaborative interface design with real-time multiplayer in the browser.', 'https://www.figma.com', ['UI', 'Collaboration'], 'Freemium', 'purple'],
  ['Framer', 'Design', 'Design and publish production websites without writing code.', 'https://www.framer.com', ['Websites', 'No code'], 'Freemium', 'blue'],
  ['Webflow', 'Design', 'Visual site builder with a CMS and fine control over layout.', 'https://webflow.com', ['No code', 'CMS'], 'Paid', 'blue'],
  ['Canva', 'Design', 'Template-driven design for social, print and quick marketing assets.', 'https://www.canva.com', ['Templates', 'Graphics'], 'Freemium', 'purple'],
  ['Excalidraw', 'Design', 'Virtual whiteboard with a deliberately hand-drawn, low-pressure feel.', 'https://excalidraw.com', ['Whiteboard', 'Open source'], 'Free', 'blue'],
  ['tldraw', 'Design', 'Minimal infinite canvas for diagrams, wireframes and thinking out loud.', 'https://www.tldraw.com', ['Canvas', 'Open source'], 'Free', 'green'],
  ['Coolors', 'Design', 'Generates colour palettes quickly, with palette locking as you go.', 'https://coolors.co', ['Colour', 'Palettes'], 'Free', 'purple'],
  ['Unsplash', 'Design', 'High-quality photography free for commercial use.', 'https://unsplash.com', ['Photos', 'Free'], 'Free', 'green'],
  ['Pexels', 'Design', 'Large library of free stock photos and video clips.', 'https://www.pexels.com', ['Photos', 'Video'], 'Free', 'green'],
  ['Google Fonts', 'Design', 'Open-source font library with variable families and web fonts.', 'https://fonts.google.com', ['Typography', 'Free'], 'Free', 'blue'],
  ['Iconify', 'Design', 'Unified search across many open-source icon sets.', 'https://icon-sets.iconify.design', ['Icons', 'Open source'], 'Free', 'amber'],
  ['LottieFiles', 'Design', 'Lightweight animated icons and illustrations in vector format.', 'https://lottiefiles.com', ['Animation', 'Vector'], 'Freemium', 'purple'],
  ['Remove.bg', 'Design', 'Automatic background removal for photos in one click.', 'https://www.remove.bg', ['Images', 'Utility'], 'Freemium', 'green'],
  ['Photopea', 'Design', 'Browser-based image editor that opens PSD and Sketch files.', 'https://www.photopea.com', ['Editing', 'Free'], 'Free', 'blue'],
  ['Spline', 'Design', 'Design and export 3D scenes for the web without a 3D background.', 'https://spline.design', ['3D', 'Web'], 'Freemium', 'purple'],

  // Education
  ['freeCodeCamp', 'Education', 'Full curriculum of web development with certifications, free to complete.', 'https://www.freecodecamp.org', ['Coding', 'Certification'], 'Free', 'green'],
  ['Khan Academy', 'Education', 'Free lessons across maths, science, computing and the humanities.', 'https://www.khanacademy.org', ['Courses', 'Free'], 'Free', ''],
  ['Coursera', 'Education', 'Degree and certificate programmes from university partners.', 'https://www.coursera.org', ['Degrees', 'Certificates'], 'Freemium', 'blue'],
  ['edX', 'Education', 'University-levelled courses, professional certificates and microcredentials.', 'https://www.edx.org', ['Courses', 'University'], 'Freemium', 'blue'],
  ['MIT OpenCourseWare', 'Education', 'Course materials from MIT, including assignments and exams.', 'https://ocw.mit.edu', ['University', 'Materials'], 'Free', 'red'],
  ['Duolingo', 'Education', 'Gamified language courses with short daily practice.', 'https://www.duolingo.com', ['Languages', 'Gamified'], 'Freemium', 'green'],
  ['Anki', 'Education', 'Spaced-repetition flashcards with a powerful scheduling algorithm.', 'https://apps.ankiweb.net', ['Flashcards', 'Memory'], 'Free', 'blue'],
  ['Brilliant', 'Education', 'Interactive problem-solving courses in maths, science and CS.', 'https://brilliant.org', ['Interactive', 'STEM'], 'Paid', 'purple'],
  ['Exercism', 'Education', 'Free mentoring and practice tracks for programming languages.', 'https://exercism.org', ['Practice', 'Mentorship'], 'Free', 'green'],
  ['Project Gutenberg', 'Education', 'Public-domain books in open formats, free to download legally.', 'https://www.gutenberg.org', ['Books', 'Public domain'], 'Free', 'amber'],
  ['OpenStax', 'Education', 'Peer-reviewed open textbooks across science and maths.', 'https://openstax.org', ['Textbooks', 'Free'], 'Free', 'amber'],
  ['Scratch', 'Education', 'Block-based programming environment aimed at first-time coders.', 'https://scratch.mit.edu', ['Beginners', 'Creative'], 'Free', 'amber'],

  // Productivity
  ['Notion', 'Productivity', 'Documents, databases and project boards in a single workspace.', 'https://www.notion.so', ['Notes', 'Wiki'], 'Freemium', ''],
  ['Obsidian', 'Productivity', 'Local-first markdown notes with a large plugin ecosystem.', 'https://obsidian.md', ['Notes', 'Markdown'], 'Freemium', 'purple'],
  ['Logseq', 'Productivity', 'Outliner-based notes built around daily journaling and backlinks.', 'https://logseq.com', ['Notes', 'Outliner'], 'Free', 'blue'],
  ['Anytype', 'Productivity', 'Local-first workspace that keeps your data on your own devices.', 'https://anytype.io', ['Local first', 'Notes'], 'Freemium', 'green'],
  ['Todoist', 'Productivity', 'Task manager with natural-language dates and shared projects.', 'https://todoist.com', ['Tasks', 'Cross platform'], 'Freemium', 'red'],
  ['Things', 'Productivity', 'Polished task manager for Apple platforms with a deliberate design.', 'https://culturedcode.com/things/', ['Tasks', 'Apple'], 'Paid', 'blue'],
  ['Trello', 'Productivity', 'Kanban boards that are quick enough to set up in under a minute.', 'https://trello.com', ['Kanban', 'Teams'], 'Freemium', 'blue'],
  ['Asana', 'Productivity', 'Project and task management with timelines, goals and reporting.', 'https://asana.com', ['Projects', 'Teams'], 'Freemium', 'purple'],
  ['Linear', 'Productivity', 'Fast issue tracker built specifically for software product teams.', 'https://linear.app', ['Issues', 'Engineering'], 'Freemium', 'purple'],
  ['Craft', 'Productivity', 'Notebook-style documents with flexible block editing and sharing.', 'https://www.craft.do', ['Documents', 'Collaboration'], 'Freemium', 'blue'],
  ['Airtable', 'Productivity', 'Spreadsheet-database hybrid for lightweight operational tracking.', 'https://www.airtable.com', ['Database', 'No code'], 'Freemium', 'green'],
  ['Superhuman', 'Productivity', 'Keyboard-first email client built for very high inbox volume.', 'https://superhuman.com', ['Email', 'Keyboard'], 'Paid', 'amber'],
  ['Raycast', 'Productivity', 'Extensible launcher for macOS that replaces several utilities at once.', 'https://www.raycast.com', ['Launcher', 'macOS'], 'Freemium', 'amber'],

  // Business
  ['Slack', 'Business', 'Channel-based team messaging with a large app directory.', 'https://slack.com', ['Messaging', 'Teams'], 'Freemium', 'purple'],
  ['Zoom', 'Business', 'Video meetings, webinars and phone for distributed teams.', 'https://zoom.us', ['Meetings', 'Video'], 'Freemium', 'blue'],
  ['Stripe', 'Business', 'Payments infrastructure with one of the best developer APIs around.', 'https://stripe.com', ['Payments', 'API'], 'Paid', 'purple'],
  ['HubSpot', 'Business', 'Combined CRM, marketing and sales tooling for small teams.', 'https://www.hubspot.com', ['CRM', 'Marketing'], 'Freemium', 'orange'],
  ['Intercom', 'Business', 'Customer messaging, help centre and support automation in one place.', 'https://www.intercom.com', ['Support', 'Chat'], 'Paid', 'blue'],
  ['Miro', 'Business', 'Collaborative whiteboard for workshops, mapping and planning.', 'https://miro.com', ['Whiteboard', 'Meetings'], 'Freemium', 'amber'],
  ['Loom', 'Business', 'Async video messaging so updates do not need a meeting.', 'https://www.loom.com', ['Video', 'Async'], 'Freemium', 'purple'],
  ['Calendly', 'Business', 'Scheduling links that handle availability and time zones.', 'https://calendly.com', ['Scheduling', 'Meetings'], 'Freemium', 'blue'],
  ['Typeform', 'Business', 'Conversational form builder that feels better than a contact form.', 'https://www.typeform.com', ['Forms', 'Marketing'], 'Freemium', 'amber'],
  ['Zapier', 'Business', 'Connects thousands of apps with automated triggers and actions.', 'https://zapier.com', ['Automation', 'Integrations'], 'Freemium', 'orange'],
  ['Shopify', 'Business', 'Storefront and checkout platform for physical and digital goods.', 'https://www.shopify.com', ['E-commerce', 'Storefront'], 'Paid', 'green'],

  // Finance
  ['YNAB', 'Finance', 'Envelope budgeting method where every unit of money gets assigned a job.', 'https://www.ynab.com', ['Budgeting', 'Personal'], 'Paid', 'green'],
  ['PocketGuard', 'Finance', 'Open-source personal finance manager with no account required.', 'https://pocketguard.com', ['Budgeting', 'Open source'], 'Free', 'green'],
  ['Wise', 'Finance', 'Multi-currency accounts with low, transparent conversion fees.', 'https://wise.com', ['Payments', 'Currency'], 'Freemium', 'green'],
  ['Mercury', 'Finance', 'Business banking built for startups, with cards and accounting hooks.', 'https://mercury.com', ['Banking', 'Startups'], 'Free', 'blue'],
  ['QuickBooks', 'Finance', 'Long-established accounting software for small and mid businesses.', 'https://quickbooks.intuit.com', ['Accounting', 'Invoicing'], 'Paid', 'green'],
  ['CoinGecko', 'Finance', 'Live cryptocurrency prices, market data and charts.', 'https://www.coingecko.com', ['Crypto', 'Markets'], 'Free', 'amber'],
  ['TradingView', 'Finance', 'Charts, technical analysis and market news across many asset classes.', 'https://www.tradingview.com', ['Charts', 'Markets'], 'Freemium', 'blue'],
  ['FRED', 'Finance', 'St. Louis Fed database of long-run economic and financial series.', 'https://fred.stlouisfed.org', ['Economics', 'Data'], 'Free', 'blue'],
  ['Alpha Vantage', 'Finance', 'Free API access to stock, forex and commodity data.', 'https://www.alphavantage.co', ['API', 'Market data'], 'Free tier', 'amber'],
  ['Robinhood', 'Finance', 'Commission-free retail brokerage alongside fractional stock investing.', 'https://robinhood.com', ['Investing', 'Brokerage'], 'Free', 'green'],

  // Cloud & Hosting
  ['AWS', 'Cloud & Hosting', 'The widest cloud platform, from single instances to global scale.', 'https://aws.amazon.com', ['Cloud', 'Infrastructure'], 'Pay as you go', 'amber'],
  ['Google Cloud', 'Cloud & Hosting', 'GCP with strong data, AI and Kubernetes offerings.', 'https://cloud.google.com', ['Cloud', 'Kubernetes'], 'Pay as you go', 'blue'],
  ['Cloudflare', 'Cloud & Hosting', 'CDN, DNS and edge compute that fronts most of the web.', 'https://www.cloudflare.com', ['CDN', 'DNS'], 'Freemium', 'amber'],
  ['Vercel', 'Cloud & Hosting', 'Deployment platform built around Next.js and preview deploys.', 'https://vercel.com', ['Deployment', 'Frontend'], 'Freemium', ''],
  ['Netlify', 'Cloud & Hosting', 'Git-connected hosting with a generous free tier for static sites.', 'https://www.netlify.com', ['Hosting', 'Static'], 'Freemium', 'green'],
  ['Supabase', 'Cloud & Hosting', 'Postgres, auth, storage and realtime in one open-source platform.', 'https://supabase.com', ['Database', 'Backend'], 'Freemium', 'green'],
  ['DigitalOcean', 'Cloud & Hosting', 'Simple, predictable pricing for VMs, droplets and managed databases.', 'https://www.digitalocean.com', ['VPS', 'Cloud'], 'Pay as you go', 'purple'],
  ['Hetzner', 'Cloud & Hosting', 'European cloud provider known for strong price-to-performance.', 'https://www.hetzner.com', ['VPS', 'Value'], 'Pay as you go', 'purple'],
  ['Fly.io', 'Cloud & Hosting', 'Deploy apps close to users across multiple regions.', 'https://fly.io', ['Deployment', 'Edge'], 'Pay as you go', 'purple'],
  ['Neon', 'Cloud & Hosting', 'Serverless Postgres that scales to zero when idle.', 'https://neon.tech', ['Database', 'Serverless'], 'Freemium', 'green'],
  ['GitHub Pages', 'Cloud & Hosting', 'Free static hosting straight from a repository, with Jekyll support.', 'https://pages.github.com', ['Hosting', 'Free'], 'Free', 'blue'],

  // Software
  ['Visual Studio Code', 'Software', 'Extensible editor with debugging and a very large extension market.', 'https://code.visualstudio.com', ['Editor', 'Extensions'], 'Free', 'blue'],
  ['GIMP', 'Software', 'Long-standing open-source image editor with layers and scripting.', 'https://www.gimp.org', ['Image', 'Open source'], 'Free', 'green'],
  ['Krita', 'Software', 'Digital painting app built for illustrators and concept artists.', 'https://krita.org', ['Illustration', 'Open source'], 'Free', 'purple'],
  ['Inkscape', 'Software', 'Vector graphics editor following the SVG standard closely.', 'https://inkscape.org', ['Vector', 'Open source'], 'Free', 'amber'],
  ['Blender', 'Software', 'Full 3D suite for modelling, animation, rendering and compositing.', 'https://www.blender.org', ['3D', 'Open source'], 'Free', 'orange'],
  ['DaVinci Resolve', 'Software', 'Professional video editing and colour grading with a free edition.', 'https://www.blackmagicdesign.com/products/davinciresolve', ['Video', 'Editing'], 'Freemium', 'amber'],
  ['Audacity', 'Software', 'Multi-track audio recorder and editor for podcasts and quick edits.', 'https://www.audacityteam.org', ['Audio', 'Open source'], 'Free', 'blue'],
  ['HandBrake', 'Software', 'Video transcoder for producing smaller, widely compatible files.', 'https://handbrake.fr', ['Video', 'Utility'], 'Free', 'green'],
  ['VLC', 'Software', 'Media player that opens almost every audio and video format.', 'https://www.videolan.org/vlc', ['Player', 'Open source'], 'Free', 'orange'],
  ['7-Zip', 'Software', 'Small, fast archiver with excellent compression ratios.', 'https://www.7-zip.org', ['Utility', 'Compression'], 'Free', 'blue'],
  ['mpv', 'Software', 'Minimal, scriptable media player popular for keyboard control.', 'https://mpv.io', ['Player', 'Open source'], 'Free', 'red'],
  ['Zotero', 'Software', 'Reference manager that captures citations and syncs your library.', 'https://www.zotero.org', ['References', 'Research'], 'Free', 'red'],
  ['Syncthing', 'Software', 'Continuous file sync between your own devices with no cloud middleman.', 'https://syncthing.net', ['Sync', 'Open source'], 'Free', 'green'],

  // Media
  ['YouTube', 'Media', 'The largest video hosting platform on the public web.', 'https://www.youtube.com', ['Video', 'Streaming'], 'Free', 'red'],
  ['Vimeo', 'Media', 'Video hosting favoured by filmmakers and studios for embedding.', 'https://vimeo.com', ['Video', 'Hosting'], 'Freemium', 'blue'],
  ['Twitch', 'Media', 'Live streaming platform built around gaming and creators.', 'https://www.twitch.tv', ['Live', 'Streaming'], 'Free', 'purple'],
  ['Spotify', 'Media', 'Music and podcast streaming with strong discovery features.', 'https://www.spotify.com', ['Music', 'Podcasts'], 'Freemium', 'green'],
  ['Bandcamp', 'Media', 'Direct-to-fan store for independent music and physical releases.', 'https://bandcamp.com', ['Music', 'Artists'], 'Pay what you want', 'blue'],
  ['Plex', 'Media', 'Runs a personal media server you can stream from anywhere.', 'https://www.plex.tv', ['Streaming', 'Self-hosted'], 'Freemium', 'amber'],
  ['Jellyfin', 'Media', 'Free software media server with no paid tier and no account required.', 'https://jellyfin.org', ['Self-hosted', 'Open source'], 'Free', 'purple'],
  ['Letterboxd', 'Media', 'Social film diary with lists, reviews and a strong community.', 'https://letterboxd.com', ['Films', 'Community'], 'Freemium', 'green'],
  ['Goodreads', 'Media', 'Reading tracker and review site with a huge catalogue.', 'https://www.goodreads.com', ['Books', 'Community'], 'Free', 'amber'],
  ['Pocket Casts', 'Media', 'Podcast client with strong cross-platform sync and queueing.', 'https://pocketcasts.com', ['Podcasts', 'Sync'], 'Freemium', 'purple'],
  ['Audible', 'Media', 'Large audiobook subscription catalogue, often bundled with Amazon.', 'https://www.audible.com', ['Audiobooks', 'Subscription'], 'Paid', 'orange'],
  ['Libby', 'Media', 'Free digital lending library app connected to local public libraries.', 'https://libbyapp.com', ['Books', 'Libraries'], 'Free', 'blue'],
  ['Internet Archive', 'Media', 'Non-profit library of books, films, software and web pages.', 'https://archive.org', ['Archive', 'Public domain'], 'Free', 'amber'],
  ['Are.na', 'Media', 'Quiet, block-based research tool for collecting references.', 'https://www.are.na', ['Research', 'Visual'], 'Freemium', 'green'],

  // Gaming
  ['Steam', 'Gaming', 'Valve’s store, launcher and library, plus Proton for Linux play.', 'https://store.steampowered.com', ['Store', 'Library'], 'Free', 'blue'],
  ['itch.io', 'Gaming', 'Indie storefront and browser-play platform with a generous revenue share.', 'https://itch.io', ['Indie', 'Browser games'], 'Free', 'red'],
  ['GOG', 'Gaming', 'DRM-free store with a strong catalogue of older PC classics.', 'https://www.gog.com', ['Store', 'DRM free'], 'Free', 'purple'],
  ['Epic Games Store', 'Gaming', 'Store with weekly free titles and Unreal Engine included.', 'https://store.epicgames.com', ['Store', 'Free games'], 'Free', 'blue'],
  ['ProtonDB', 'Gaming', 'Community compatibility reports for running Windows games on Linux.', 'https://www.protondb.com', ['Linux', 'Compatibility'], 'Free', 'blue'],
  ['PCGamingWiki', 'Gaming', 'Community wiki of fixes, mods and performance notes per title.', 'https://www.pcgamingwiki.com', ['Wiki', 'Fixes'], 'Free', 'green'],
  ['Nexus Mods', 'Gaming', 'Very large mod repository with a game-specific version system.', 'https://www.nexusmods.com', ['Mods', 'Community'], 'Free', 'amber'],
  ['Speedrun.com', 'Gaming', 'Leaderboards and timing tools for speedrunning records.', 'https://www.speedrun.com', ['Leaderboards', 'Community'], 'Free', 'orange'],
  ['IsThereAnyDeal', 'Gaming', 'Price history and aggregation across PC storefronts.', 'https://isthereanydeal.com', ['Deals', 'Price tracking'], 'Free', 'blue'],
  ['Xbox Game Pass', 'Gaming', 'Subscription giving access to a large rotating PC and console catalogue.', 'https://www.xbox.com/en-us/xbox-game-pass', ['Subscription', 'Console'], 'Paid', 'green'],

  // OSINT & Research
  ['SearXNG', 'OSINT & Research', 'Metasearch engine you can self-host to aggregate many indexes.', 'https://searx.be', ['Search', 'Privacy'], 'Free', 'blue'],
  ['Exa', 'OSINT & Research', 'Semantic web search that returns results in a structure suited to models.', 'https://exa.ai', ['Search', 'Semantic'], 'Freemium', 'purple'],
  ['Marginalia', 'OSINT & Research', 'Search engine indexing independent and non-commercial pages.', 'https://search.marginalia.nu', ['Search', 'Independent'], 'Free', 'green'],
  ['Wayback Machine', 'OSINT & Research', 'Snapshots of web pages going back to the mid-1990s.', 'https://web.archive.org', ['Archive', 'History'], 'Free', 'blue'],
  ['IPinfo', 'OSINT & Research', 'IP geolocation, ASN and hostname data with a free tier.', 'https://ipinfo.io', ['IP', 'Geolocation'], 'Freemium', 'amber'],
  ['BuiltWith', 'OSINT & Research', 'Profiles websites by the technologies and providers they use.', 'https://builtwith.com', ['Fingerprinting', 'Domains'], 'Freemium', 'purple'],
  ['Netlas', 'OSINT & Research', 'Searches internet-wide scan data for hosts, certificates and services.', 'https://app.netlas.io', ['Recon', 'Certificates'], 'Freemium', 'amber'],
  ['urlscan.io', 'OSINT & Research', 'Submits a URL for a recorded browser scan with screenshots.', 'https://urlscan.io', ['Sandbox', 'Screenshots'], 'Free', 'blue'],
  ['Semantic Scholar', 'OSINT & Research', 'AI-assisted literature search across academic papers.', 'https://www.semanticscholar.org', ['Papers', 'Research'], 'Free', 'blue'],
  ['arXiv', 'OSINT & Research', 'Open preprints in physics, maths, computer science and more.', 'https://arxiv.org', ['Preprints', 'Research'], 'Free', 'amber'],
  ['OpenStreetMap', 'OSINT & Research', 'Open map data you can query, download and self-host.', 'https://www.openstreetmap.org', ['Maps', 'Open data'], 'Free', 'green'],
  ['Wikidata', 'OSINT & Research', 'Structured, queryable database backing Wikipedia knowledge.', 'https://www.wikidata.org', ['Knowledge', 'Open data'], 'Free', 'blue'],
  ['Common Crawl', 'OSINT & Research', 'Open datasets of web pages, useful for large-scale analysis.', 'https://commoncrawl.org', ['Datasets', 'Research'], 'Free', 'blue'],

  // Science
  ['NASA', 'Science', 'Mission imagery, datasets and educational material from NASA.', 'https://www.nasa.gov', ['Space', 'Data'], 'Free', 'blue'],
  ['Nature', 'Science', 'Journal publishing significant original research across the sciences.', 'https://www.nature.com', ['Research', 'Journal'], 'Paid', 'red'],
  ['PubMed', 'Science', 'Free index of biomedical and life-science literature.', 'https://pubmed.ncbi.nlm.nih.gov', ['Medicine', 'Research'], 'Free', 'purple'],
  ['Wolfram Alpha', 'Science', 'Computational engine that answers algebraic and factual queries.', 'https://www.wolframalpha.com', ['Computation', 'Reference'], 'Freemium', 'amber'],
  ['PhET', 'Science', 'Interactive physics, chemistry and biology simulations from Colorado.', 'https://phet.colorado.edu', ['Simulation', 'Education'], 'Free', 'green'],
  ['Desmos', 'Science', 'Graphing calculator with sliders and shareable single-link activities.', 'https://www.desmos.com/calculator', ['Maths', 'Graphing'], 'Free', 'amber'],
  ['GeoGebra', 'Science', 'Dynamic geometry, algebra and statistics software for classrooms.', 'https://www.geogebra.org', ['Maths', 'Classroom'], 'Free', 'blue'],
  ['Quanta Magazine', 'Science', 'Long-form reporting on physics, biology, maths and computing.', 'https://www.quantamagazine.org', ['Journalism', 'Research'], 'Free', 'amber'],
  ['Our World in Data', 'Science', 'Clear charts built on open datasets for long-run trends.', 'https://ourworldindata.org', ['Data', 'Charts'], 'Free', 'blue'],
  ['Observable', 'Science', 'Data visualisation and mapping notebooks in the browser.', 'https://observablehq.com', ['Data viz', 'Notebooks'], 'Free', 'purple'],
  ['iNaturalist', 'Science', 'Biodiversity observations identified with community verification.', 'https://www.inaturalist.org', ['Nature', 'Community'], 'Free', 'green'],
  ['SciPy', 'Science', 'Python library for scientific computing, optimisation and signal processing.', 'https://scipy.org', ['Python', 'Science'], 'Free', 'blue'],

  // Career & Jobs
  ['LinkedIn', 'Career & Jobs', 'Professional network, job search and company research.', 'https://www.linkedin.com', ['Networking', 'Jobs'], 'Freemium', 'blue'],
  ['Indeed', 'Career & Jobs', 'Largest general-purpose job board by listing volume.', 'https://www.indeed.com', ['Jobs', 'Board'], 'Free', 'blue'],
  ['Wellfound', 'Career & Jobs', 'Startup-focused job board with salary and equity filters.', 'https://wellfound.com', ['Startups', 'Jobs'], 'Free', 'purple'],
  ['Remote OK', 'Career & Jobs', 'Huge index of remote jobs with filters for time zone and stack.', 'https://remoteok.com', ['Remote', 'Jobs'], 'Free', 'green'],
  ['We Work Remotely', 'Career & Jobs', 'Curated remote job listings across many categories.', 'https://weworkremotely.com', ['Remote', 'Curated'], 'Free', 'green'],
  ['Levels.fyi', 'Career & Jobs', 'Compensation data by company, level and location.', 'https://www.levels.fyi', ['Salaries', 'Data'], 'Free', 'blue'],
  ['Glassdoor', 'Career & Jobs', 'Company reviews, interview questions and salary reports.', 'https://www.glassdoor.com', ['Reviews', 'Salaries'], 'Freemium', 'green'],
  ['Y Combinator Jobs', 'Career & Jobs', 'Board of roles at companies backed by Y Combinator.', 'https://www.ycombinator.com/jobs', ['Startups', 'Board'], 'Free', 'amber'],
  ['Otta', 'Career & Jobs', 'High-signal application tracker built for new graduates.', 'https://otta.com', ['Applications', 'Early career'], 'Free', 'purple'],

  // Marketing
  ['Google Analytics', 'Marketing', 'Free web analytics with a large reporting and tag ecosystem.', 'https://analytics.google.com', ['Analytics', 'Free'], 'Freemium', 'amber'],
  ['Plausible', 'Marketing', 'Lightweight open-source analytics with no cookies and no tracking.', 'https://plausible.io', ['Analytics', 'Privacy'], 'Paid', 'blue'],
  ['Ahrefs', 'Marketing', 'Backlink, keyword and content research built for SEO teams.', 'https://ahrefs.com', ['SEO', 'Backlinks'], 'Paid', 'orange'],
  ['Semrush', 'Marketing', 'Search, social and advertising intelligence for marketers.', 'https://www.semrush.com', ['SEO', 'Ads'], 'Paid', 'orange'],
  ['Mailchimp', 'Marketing', 'Email marketing with marketing automation and a free tier.', 'https://mailchimp.com', ['Email', 'Automation'], 'Freemium', 'amber'],
  ['Kit', 'Marketing', 'Creator-focused newsletter and commerce platform.', 'https://kit.com', ['Newsletter', 'Creators'], 'Freemium', 'green'],
  ['Buffer', 'Marketing', 'Schedules and publishes social posts across several networks.', 'https://buffer.com', ['Social', 'Scheduling'], 'Freemium', 'blue'],
  ['Hotjar', 'Marketing', 'Heatmaps, session recordings and surveys for conversion insight.', 'https://www.hotjar.com', ['Heatmaps', 'UX'], 'Freemium', 'amber'],
  ['Klaviyo', 'Marketing', 'Data-heavy email and SMS marketing for ecommerce brands.', 'https://www.klaviyo.com', ['Email', 'Ecommerce'], 'Paid', 'green'],

  // Social Media
  ['X', 'Social Media', 'Microblogging platform with a large real-time conversation.', 'https://x.com', ['Microblog', 'News'], 'Freemium', ''],
  ['Reddit', 'Social Media', 'Topic-based communities covering an enormous range of niches.', 'https://www.reddit.com', ['Communities', 'Discussion'], 'Free', 'orange'],
  ['Bluesky', 'Social Media', 'Decentralised social network built on the AT Protocol.', 'https://bsky.app', ['Decentralised', 'Open'], 'Free', 'blue'],
  ['Mastodon', 'Social Media', 'Federated social network spread across independent instances.', 'https://joinmastodon.org', ['Federated', 'Open'], 'Free', 'purple'],
  ['Discord', 'Social Media', 'Persistent voice, video and text servers for communities.', 'https://discord.com', ['Voice', 'Communities'], 'Freemium', 'blue'],
  ['Telegram', 'Social Media', 'Cloud messaging with large group and broadcast support.', 'https://telegram.org', ['Messaging', 'Channels'], 'Free', 'blue'],
  ['Signal', 'Social Media', 'End-to-end encrypted messenger focused on metadata protection.', 'https://signal.org', ['Encrypted', 'Messaging'], 'Free', 'green'],
  ['Tumblr', 'Social Media', 'Long-running blogging community with strong reblog culture.', 'https://www.tumblr.com', ['Blogging', 'Community'], 'Free', 'blue'],
  ['Lemmy', 'Social Media', 'Federated link aggregator with community voting.', 'https://join-lemmy.org', ['Federated', 'Links'], 'Free', 'green'],

  // Web Tools
  ['PageSpeed Insights', 'Web Tools', 'Google performance diagnostics for Core Web Vitals.', 'https://pagespeed.web.dev', ['Performance', 'Free'], 'Free', 'green'],
  ['GTmetrix', 'Web Tools', 'Detailed performance breakdown with historical comparisons.', 'https://www.gtmetrix.com', ['Performance', 'Metrics'], 'Freemium', 'green'],
  ['W3C Markup Validator', 'Web Tools', 'Checks HTML validity against the current specification.', 'https://validator.w3.org/nu/', ['HTML', 'Validation'], 'Free', 'blue'],
  ['Rich Results Test', 'Web Tools', 'Validates structured data for search-result eligibility.', 'https://search.google.com/test/rich-results', ['SEO', 'Schema'], 'Free', 'blue'],
  ['Diffchecker', 'Web Tools', 'Side-by-side text comparison that highlights exactly what changed.', 'https://www.diffchecker.com', ['Text', 'Utility'], 'Free', 'amber'],
  ['TinyPNG', 'Web Tools', 'Lossy image compression that keeps quality visually intact.', 'https://tinypng.com', ['Images', 'Compression'], 'Free', 'green'],
  ['Guerrilla Mail', 'Web Tools', 'Disposable inboxes for testing signup and email flows.', 'https://www.guerrillamail.com', ['Email', 'Testing'], 'Free', 'amber'],
  ['httpstatus.io', 'Web Tools', 'Inspects the status codes a URL returns across a redirect chain.', 'https://httpstatus.io', ['HTTP', 'Utility'], 'Free', 'blue'],
  ['JSON Formatter', 'Web Tools', 'Validates and pretty-prints JSON directly in the browser.', 'https://jsonformatter.org', ['JSON', 'Utility'], 'Free', 'amber'],
  ['Cloudflare Radar', 'Web Tools', 'Free API exposing global traffic and threat data on the internet.', 'https://radar.cloudflare.com', ['API', 'Free'], 'Free', 'orange'],
  ['MDN Compat Data', 'Web Tools', 'Machine-readable browser compatibility data on GitHub.', 'https://github.com/mdn/browser-compat-data', ['Data', 'Open source'], 'Free', 'blue']
];

window.LINKFINDER_SITES = S.map(function (row) {
  const slug = row[0].toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  return {
    slug: slug,
    name: row[0],
    letter: row[0].length <= 2 ? row[0] : row[0][0],
    desc: row[2],
    cat: row[1],
    url: row[3],
    tags: row[4],
    price: row[5],
    color: row[6] || '',
    linkStatus: 'unchecked'
  };
});
